apiVersion: 1

datasources:
  - name: Wazuh-Indexer
    type: grafana-opensearch-datasource
    uid: wazuh-indexer-ds
    access: proxy
    url: https://wazuh-indexer:9200
    jsonData:
      database: wazuh-alerts-*
      flavor: opensearch
      maxConcurrentShardRequests: 5
      timeField: "@timestamp"
      tlsSkipVerify: true
      version: "2.10.0"
      pplEnabled: true
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: admin
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    uid: loki-ds
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
