[sase_lab:children]
frr_routers
firewalls

[frr_routers]
hq-rtr ansible_host=clab-sase-lab-hq-rtr
branch-rtr ansible_host=clab-sase-lab-branch-rtr
remote-rtr ansible_host=clab-sase-lab-remote-rtr

[firewalls]
hq-fw ansible_host=clab-sase-lab-hq-fw
branch-fw ansible_host=clab-sase-lab-branch-fw

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_connection=docker
